<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace TestRespMsg;

/**
 * Protobuf type <code>TestRespMsg.eMsgType</code>
 */
class eMsgType
{
    /**
     * Generated from protobuf enum <code>MSG_TYPE_TEST_THROUGHPUT_RESP = 0;</code>
     */
    const MSG_TYPE_TEST_THROUGHPUT_RESP = 0;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_TEST_STATS_RESP = 1;</code>
     */
    const MSG_TYPE_TEST_STATS_RESP = 1;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_TEST_THROUGHPUT_WITH_STATS_RESP = 2;</code>
     */
    const MSG_TYPE_TEST_THROUGHPUT_WITH_STATS_RESP = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(eMsgType::class, \TestRespMsg_eMsgType::class);

