<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace TestMsg;

/**
 * Protobuf type <code>TestMsg.eMsgType</code>
 */
class eMsgType
{
    /**
     * Generated from protobuf enum <code>MSG_TYPE_TEST_THROUGHPUT = 0;</code>
     */
    const MSG_TYPE_TEST_THROUGHPUT = 0;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_TEST_RESTART_DEVICE = 1;</code>
     */
    const MSG_TYPE_TEST_RESTART_DEVICE = 1;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_TEST_MUTE_BT = 2;</code>
     */
    const MSG_TYPE_TEST_MUTE_BT = 2;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_TEST_STATS = 3;</code>
     */
    const MSG_TYPE_TEST_STATS = 3;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_TEST_CLR_STATS = 4;</code>
     */
    const MSG_TYPE_TEST_CLR_STATS = 4;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_TEST_THROUGHPUT_WITH_STATS = 5;</code>
     */
    const MSG_TYPE_TEST_THROUGHPUT_WITH_STATS = 5;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(eMsgType::class, \TestMsg_eMsgType::class);

