<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BTChipDataMsg</code>
 */
class BTChipDataMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.BTChipDataMsg.eMsgType msg_type = 1;</code>
     */
    private $msg_type = 0;
    protected $OneOfMsg;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $msg_type
     *     @type \SensorDataMsg $sensordata
     *     @type \GetConfigMsg $getconfigmsg
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mainmessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.BTChipDataMsg.eMsgType msg_type = 1;</code>
     * @return int
     */
    public function getMsgType()
    {
        return $this->msg_type;
    }

    /**
     * Generated from protobuf field <code>.BTChipDataMsg.eMsgType msg_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgType($var)
    {
        GPBUtil::checkEnum($var, \BTChipDataMsg_eMsgType::class);
        $this->msg_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.SensorDataMsg sensordata = 3;</code>
     * @return \SensorDataMsg
     */
    public function getSensordata()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.SensorDataMsg sensordata = 3;</code>
     * @param \SensorDataMsg $var
     * @return $this
     */
    public function setSensordata($var)
    {
        GPBUtil::checkMessage($var, \SensorDataMsg::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GetConfigMsg getconfigmsg = 4;</code>
     * @return \GetConfigMsg
     */
    public function getGetconfigmsg()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>.GetConfigMsg getconfigmsg = 4;</code>
     * @param \GetConfigMsg $var
     * @return $this
     */
    public function setGetconfigmsg($var)
    {
        GPBUtil::checkMessage($var, \GetConfigMsg::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getOneOfMsg()
    {
        return $this->whichOneof("OneOfMsg");
    }

}

