<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

if (false) {
    /**
     * This class is deprecated. Use BTChipDataMsg\eMsgType instead.
     * @deprecated
     */
    class BTChipDataMsg_eMsgType {}
}
class_exists(BTChipDataMsg\eMsgType::class);
@trigger_error('BTChipDataMsg_eMsgType is deprecated and will be removed in the next major release. Use BTChipDataMsg\eMsgType instead', E_USER_DEPRECATED);

