<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

if (false) {
    /**
     * This class is deprecated. Use GetConfigMsg\eMsgType instead.
     * @deprecated
     */
    class GetConfigMsg_eMsgType {}
}
class_exists(GetConfigMsg\eMsgType::class);
@trigger_error('GetConfigMsg_eMsgType is deprecated and will be removed in the next major release. Use GetConfigMsg\eMsgType instead', E_USER_DEPRECATED);

