<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

if (false) {
    /**
     * This class is deprecated. Use MainMsg\eMsgType instead.
     * @deprecated
     */
    class MainMsg_eMsgType {}
}
class_exists(MainMsg\eMsgType::class);
@trigger_error('MainMsg_eMsgType is deprecated and will be removed in the next major release. Use MainMsg\eMsgType instead', E_USER_DEPRECATED);

