<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

if (false) {
    /**
     * This class is deprecated. Use RMMsg\eMsgType instead.
     * @deprecated
     */
    class RMMsg_eMsgType {}
}
class_exists(RMMsg\eMsgType::class);
@trigger_error('RMMsg_eMsgType is deprecated and will be removed in the next major release. Use RMMsg\eMsgType instead', E_USER_DEPRECATED);

