<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

if (false) {
    /**
     * This class is deprecated. Use TestRespMsg\eMsgType instead.
     * @deprecated
     */
    class TestRespMsg_eMsgType {}
}
class_exists(TestRespMsg\eMsgType::class);
@trigger_error('TestRespMsg_eMsgType is deprecated and will be removed in the next major release. Use TestRespMsg\eMsgType instead', E_USER_DEPRECATED);

