<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

if (false) {
    /**
     * This class is deprecated. Use TestMsg\eMsgType instead.
     * @deprecated
     */
    class TestMsg_eMsgType {}
}
class_exists(TestMsg\eMsgType::class);
@trigger_error('TestMsg_eMsgType is deprecated and will be removed in the next major release. Use TestMsg\eMsgType instead', E_USER_DEPRECATED);

