<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TestThroughPutWithStatsRespMsg</code>
 */
class TestThroughPutWithStatsRespMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 idx = 1;</code>
     */
    private $idx = 0;
    /**
     * Generated from protobuf field <code>int32 received_packets = 2;</code>
     */
    private $received_packets = 0;
    /**
     * Generated from protobuf field <code>int32 received_bytes = 3;</code>
     */
    private $received_bytes = 0;
    /**
     * Generated from protobuf field <code>int32 first_packet_tick = 4;</code>
     */
    private $first_packet_tick = 0;
    /**
     * Generated from protobuf field <code>int32 last_packet_tick = 5;</code>
     */
    private $last_packet_tick = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $idx
     *     @type int $received_packets
     *     @type int $received_bytes
     *     @type int $first_packet_tick
     *     @type int $last_packet_tick
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mainmessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 idx = 1;</code>
     * @return int
     */
    public function getIdx()
    {
        return $this->idx;
    }

    /**
     * Generated from protobuf field <code>int32 idx = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIdx($var)
    {
        GPBUtil::checkInt32($var);
        $this->idx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 received_packets = 2;</code>
     * @return int
     */
    public function getReceivedPackets()
    {
        return $this->received_packets;
    }

    /**
     * Generated from protobuf field <code>int32 received_packets = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setReceivedPackets($var)
    {
        GPBUtil::checkInt32($var);
        $this->received_packets = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 received_bytes = 3;</code>
     * @return int
     */
    public function getReceivedBytes()
    {
        return $this->received_bytes;
    }

    /**
     * Generated from protobuf field <code>int32 received_bytes = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setReceivedBytes($var)
    {
        GPBUtil::checkInt32($var);
        $this->received_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 first_packet_tick = 4;</code>
     * @return int
     */
    public function getFirstPacketTick()
    {
        return $this->first_packet_tick;
    }

    /**
     * Generated from protobuf field <code>int32 first_packet_tick = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setFirstPacketTick($var)
    {
        GPBUtil::checkInt32($var);
        $this->first_packet_tick = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 last_packet_tick = 5;</code>
     * @return int
     */
    public function getLastPacketTick()
    {
        return $this->last_packet_tick;
    }

    /**
     * Generated from protobuf field <code>int32 last_packet_tick = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLastPacketTick($var)
    {
        GPBUtil::checkInt32($var);
        $this->last_packet_tick = $var;

        return $this;
    }

}

