<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace Sealution\Messages\RMMsg;

/**
 * Protobuf type <code>RMMsg.eMsgType</code>
 */
class eMsgType
{
    /**
     * Generated from protobuf enum <code>MSG_TYPE_SENSOR_DATA = 0;</code>
     */
    const MSG_TYPE_SENSOR_DATA = 0;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(eMsgType::class, \Sealution\Messages\RMMsg_eMsgType::class);

