<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace Sealution\Messages\MainMsg;

use UnexpectedValueException;

/**
 * Protobuf type <code>MainMsg.eMsgType</code>
 */
class eMsgType
{
    /**
     * Generated from protobuf enum <code>MSG_TYPE_SET_TIME = 0;</code>
     */
    const MSG_TYPE_SET_TIME = 0;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_GET_TIME = 1;</code>
     */
    const MSG_TYPE_GET_TIME = 1;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_TIME = 2;</code>
     */
    const MSG_TYPE_TIME = 2;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_HEARTBEAT = 3;</code>
     */
    const MSG_TYPE_HEARTBEAT = 3;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_SET_CONFIG = 4;</code>
     */
    const MSG_TYPE_SET_CONFIG = 4;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_GET_CONFIG = 5;</code>
     */
    const MSG_TYPE_GET_CONFIG = 5;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_CONFIG = 6;</code>
     */
    const MSG_TYPE_CONFIG = 6;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_TEST = 7;</code>
     */
    const MSG_TYPE_TEST = 7;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_TEST_RESP = 8;</code>
     */
    const MSG_TYPE_TEST_RESP = 8;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_RM = 9;</code>
     */
    const MSG_TYPE_RM = 9;

    private static $valueToName = [
        self::MSG_TYPE_SET_TIME => 'MSG_TYPE_SET_TIME',
        self::MSG_TYPE_GET_TIME => 'MSG_TYPE_GET_TIME',
        self::MSG_TYPE_TIME => 'MSG_TYPE_TIME',
        self::MSG_TYPE_HEARTBEAT => 'MSG_TYPE_HEARTBEAT',
        self::MSG_TYPE_SET_CONFIG => 'MSG_TYPE_SET_CONFIG',
        self::MSG_TYPE_GET_CONFIG => 'MSG_TYPE_GET_CONFIG',
        self::MSG_TYPE_CONFIG => 'MSG_TYPE_CONFIG',
        self::MSG_TYPE_TEST => 'MSG_TYPE_TEST',
        self::MSG_TYPE_TEST_RESP => 'MSG_TYPE_TEST_RESP',
        self::MSG_TYPE_RM => 'MSG_TYPE_RM',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(eMsgType::class, \Sealution/Messages\MainMsg_eMsgType::class);

