<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace Sealution\Messages;

if (false) {
    /**
     * This class is deprecated. Use Sealution\Messages\GetConfigMsg\eMsgType instead.
     * @deprecated
     */
    class GetConfigMsg_eMsgType {}
}
class_exists(GetConfigMsg\eMsgType::class);
@trigger_error('Sealution\Messages\GetConfigMsg_eMsgType is deprecated and will be removed in the next major release. Use Sealution\Messages\GetConfigMsg\eMsgType instead', E_USER_DEPRECATED);

