<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace Sealution\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GetConfigMsg</code>
 */
class GetConfigMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.GetConfigMsg.eMsgType msg_type = 1;</code>
     */
    private $msg_type = 0;
    protected $OneOfMsg;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $msg_type
     *     @type \Sealution\Messages\GetConfigGatewayGlobalMsg $config_gateway_global
     *     @type \Sealution\Messages\GetConfigSensorConfigMsg $config_sensor_config
     *     @type \Sealution\Messages\GetConfigStatusConfigMsg $config_status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mainmessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.GetConfigMsg.eMsgType msg_type = 1;</code>
     * @return int
     */
    public function getMsgType()
    {
        return $this->msg_type;
    }

    /**
     * Generated from protobuf field <code>.GetConfigMsg.eMsgType msg_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgType($var)
    {
        GPBUtil::checkEnum($var, \Sealution\Messages\GetConfigMsg_eMsgType::class);
        $this->msg_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GetConfigGatewayGlobalMsg config_gateway_global = 2;</code>
     * @return \Sealution\Messages\GetConfigGatewayGlobalMsg
     */
    public function getConfigGatewayGlobal()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.GetConfigGatewayGlobalMsg config_gateway_global = 2;</code>
     * @param \Sealution\Messages\GetConfigGatewayGlobalMsg $var
     * @return $this
     */
    public function setConfigGatewayGlobal($var)
    {
        GPBUtil::checkMessage($var, \Sealution\Messages\GetConfigGatewayGlobalMsg::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GetConfigSensorConfigMsg config_sensor_config = 3;</code>
     * @return \Sealution\Messages\GetConfigSensorConfigMsg
     */
    public function getConfigSensorConfig()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.GetConfigSensorConfigMsg config_sensor_config = 3;</code>
     * @param \Sealution\Messages\GetConfigSensorConfigMsg $var
     * @return $this
     */
    public function setConfigSensorConfig($var)
    {
        GPBUtil::checkMessage($var, \Sealution\Messages\GetConfigSensorConfigMsg::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GetConfigStatusConfigMsg config_status = 4;</code>
     * @return \Sealution\Messages\GetConfigStatusConfigMsg
     */
    public function getConfigStatus()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>.GetConfigStatusConfigMsg config_status = 4;</code>
     * @param \Sealution\Messages\GetConfigStatusConfigMsg $var
     * @return $this
     */
    public function setConfigStatus($var)
    {
        GPBUtil::checkMessage($var, \Sealution\Messages\GetConfigStatusConfigMsg::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getOneOfMsg()
    {
        return $this->whichOneof("OneOfMsg");
    }

}

