<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace Sealution\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GetConfigGatewayGlobalMsg</code>
 */
class GetConfigGatewayGlobalMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes gateway_name = 1;</code>
     */
    private $gateway_name = '';
    /**
     * Generated from protobuf field <code>uint32 gateway_powerline_connection_interval = 2;</code>
     */
    private $gateway_powerline_connection_interval = 0;
    /**
     * Generated from protobuf field <code>uint32 gateway_powerline_connection_timeout = 3;</code>
     */
    private $gateway_powerline_connection_timeout = 0;
    /**
     * Generated from protobuf field <code>bytes gateway_location = 4;</code>
     */
    private $gateway_location = '';
    /**
     * Generated from protobuf field <code>uint32 gateway_filter_configuration = 5;</code>
     */
    private $gateway_filter_configuration = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $gateway_name
     *     @type int $gateway_powerline_connection_interval
     *     @type int $gateway_powerline_connection_timeout
     *     @type string $gateway_location
     *     @type int $gateway_filter_configuration
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mainmessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes gateway_name = 1;</code>
     * @return string
     */
    public function getGatewayName()
    {
        return $this->gateway_name;
    }

    /**
     * Generated from protobuf field <code>bytes gateway_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGatewayName($var)
    {
        GPBUtil::checkString($var, False);
        $this->gateway_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 gateway_powerline_connection_interval = 2;</code>
     * @return int
     */
    public function getGatewayPowerlineConnectionInterval()
    {
        return $this->gateway_powerline_connection_interval;
    }

    /**
     * Generated from protobuf field <code>uint32 gateway_powerline_connection_interval = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setGatewayPowerlineConnectionInterval($var)
    {
        GPBUtil::checkUint32($var);
        $this->gateway_powerline_connection_interval = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 gateway_powerline_connection_timeout = 3;</code>
     * @return int
     */
    public function getGatewayPowerlineConnectionTimeout()
    {
        return $this->gateway_powerline_connection_timeout;
    }

    /**
     * Generated from protobuf field <code>uint32 gateway_powerline_connection_timeout = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setGatewayPowerlineConnectionTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->gateway_powerline_connection_timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes gateway_location = 4;</code>
     * @return string
     */
    public function getGatewayLocation()
    {
        return $this->gateway_location;
    }

    /**
     * Generated from protobuf field <code>bytes gateway_location = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setGatewayLocation($var)
    {
        GPBUtil::checkString($var, False);
        $this->gateway_location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 gateway_filter_configuration = 5;</code>
     * @return int
     */
    public function getGatewayFilterConfiguration()
    {
        return $this->gateway_filter_configuration;
    }

    /**
     * Generated from protobuf field <code>uint32 gateway_filter_configuration = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setGatewayFilterConfiguration($var)
    {
        GPBUtil::checkUint32($var);
        $this->gateway_filter_configuration = $var;

        return $this;
    }

}

