<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace Sealution\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MQTTSensorDataMsg</code>
 */
class MQTTSensorDataMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_bt = 1;</code>
     */
    private $date_time_bt = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_rm = 2;</code>
     */
    private $date_time_rm = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_cm = 3;</code>
     */
    private $date_time_cm = null;
    /**
     * Generated from protobuf field <code>int32 rssi = 4;</code>
     */
    private $rssi = 0;
    /**
     * Generated from protobuf field <code>bytes data = 5;</code>
     */
    private $data = '';
    /**
     * Generated from protobuf field <code>bytes mac_bt = 6;</code>
     */
    private $mac_bt = '';
    /**
     * Generated from protobuf field <code>bytes mac_rm = 7;</code>
     */
    private $mac_rm = '';
    /**
     * Generated from protobuf field <code>bytes mac_cm = 8;</code>
     */
    private $mac_cm = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $date_time_bt
     *     @type \Google\Protobuf\Timestamp $date_time_rm
     *     @type \Google\Protobuf\Timestamp $date_time_cm
     *     @type int $rssi
     *     @type string $data
     *     @type string $mac_bt
     *     @type string $mac_rm
     *     @type string $mac_cm
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mainmessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_bt = 1;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getDateTimeBt()
    {
        return $this->date_time_bt;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_bt = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDateTimeBt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->date_time_bt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_rm = 2;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getDateTimeRm()
    {
        return $this->date_time_rm;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_rm = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDateTimeRm($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->date_time_rm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_cm = 3;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getDateTimeCm()
    {
        return $this->date_time_cm;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_cm = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDateTimeCm($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->date_time_cm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rssi = 4;</code>
     * @return int
     */
    public function getRssi()
    {
        return $this->rssi;
    }

    /**
     * Generated from protobuf field <code>int32 rssi = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRssi($var)
    {
        GPBUtil::checkInt32($var);
        $this->rssi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 5;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes mac_bt = 6;</code>
     * @return string
     */
    public function getMacBt()
    {
        return $this->mac_bt;
    }

    /**
     * Generated from protobuf field <code>bytes mac_bt = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMacBt($var)
    {
        GPBUtil::checkString($var, False);
        $this->mac_bt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes mac_rm = 7;</code>
     * @return string
     */
    public function getMacRm()
    {
        return $this->mac_rm;
    }

    /**
     * Generated from protobuf field <code>bytes mac_rm = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setMacRm($var)
    {
        GPBUtil::checkString($var, False);
        $this->mac_rm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes mac_cm = 8;</code>
     * @return string
     */
    public function getMacCm()
    {
        return $this->mac_cm;
    }

    /**
     * Generated from protobuf field <code>bytes mac_cm = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMacCm($var)
    {
        GPBUtil::checkString($var, False);
        $this->mac_cm = $var;

        return $this;
    }

}

