<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace Sealution\Messages;

if (false) {
    /**
     * This class is deprecated. Use Sealution\Messages\RMMsg\eMsgType instead.
     * @deprecated
     */
    class RMMsg_eMsgType {}
}
class_exists(RMMsg\eMsgType::class);
@trigger_error('Sealution\Messages\RMMsg_eMsgType is deprecated and will be removed in the next major release. Use Sealution\Messages\RMMsg\eMsgType instead', E_USER_DEPRECATED);

