<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace Sealution\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TestStatsRespMsg</code>
 */
class TestStatsRespMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 msgRx = 1;</code>
     */
    private $msgRx = 0;
    /**
     * Generated from protobuf field <code>int32 msgTx = 2;</code>
     */
    private $msgTx = 0;
    /**
     * Generated from protobuf field <code>int32 msgErrors = 3;</code>
     */
    private $msgErrors = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $msgRx
     *     @type int $msgTx
     *     @type int $msgErrors
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mainmessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 msgRx = 1;</code>
     * @return int
     */
    public function getMsgRx()
    {
        return $this->msgRx;
    }

    /**
     * Generated from protobuf field <code>int32 msgRx = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgRx($var)
    {
        GPBUtil::checkInt32($var);
        $this->msgRx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 msgTx = 2;</code>
     * @return int
     */
    public function getMsgTx()
    {
        return $this->msgTx;
    }

    /**
     * Generated from protobuf field <code>int32 msgTx = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgTx($var)
    {
        GPBUtil::checkInt32($var);
        $this->msgTx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 msgErrors = 3;</code>
     * @return int
     */
    public function getMsgErrors()
    {
        return $this->msgErrors;
    }

    /**
     * Generated from protobuf field <code>int32 msgErrors = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgErrors($var)
    {
        GPBUtil::checkInt32($var);
        $this->msgErrors = $var;

        return $this;
    }

}

