<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace Sealution\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TestMuteBTMsg</code>
 */
class TestMuteBTMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool mute = 1;</code>
     */
    protected $mute = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $mute
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mainmessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool mute = 1;</code>
     * @return bool
     */
    public function getMute()
    {
        return $this->mute;
    }

    /**
     * Generated from protobuf field <code>bool mute = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setMute($var)
    {
        GPBUtil::checkBool($var);
        $this->mute = $var;

        return $this;
    }

}

