<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace Sealution\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TestThroughPutMsg</code>
 */
class TestThroughPutMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes data_pattern = 1;</code>
     */
    protected $data_pattern = '';
    /**
     * Generated from protobuf field <code>int32 nof_data_patterns_in_packet = 2;</code>
     */
    protected $nof_data_patterns_in_packet = 0;
    /**
     * Generated from protobuf field <code>int32 time_between_packets = 3;</code>
     */
    protected $time_between_packets = 0;
    /**
     * Generated from protobuf field <code>int32 nof_packets = 4;</code>
     */
    protected $nof_packets = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $data_pattern
     *     @type int $nof_data_patterns_in_packet
     *     @type int $time_between_packets
     *     @type int $nof_packets
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mainmessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes data_pattern = 1;</code>
     * @return string
     */
    public function getDataPattern()
    {
        return $this->data_pattern;
    }

    /**
     * Generated from protobuf field <code>bytes data_pattern = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDataPattern($var)
    {
        GPBUtil::checkString($var, False);
        $this->data_pattern = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 nof_data_patterns_in_packet = 2;</code>
     * @return int
     */
    public function getNofDataPatternsInPacket()
    {
        return $this->nof_data_patterns_in_packet;
    }

    /**
     * Generated from protobuf field <code>int32 nof_data_patterns_in_packet = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNofDataPatternsInPacket($var)
    {
        GPBUtil::checkInt32($var);
        $this->nof_data_patterns_in_packet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 time_between_packets = 3;</code>
     * @return int
     */
    public function getTimeBetweenPackets()
    {
        return $this->time_between_packets;
    }

    /**
     * Generated from protobuf field <code>int32 time_between_packets = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeBetweenPackets($var)
    {
        GPBUtil::checkInt32($var);
        $this->time_between_packets = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 nof_packets = 4;</code>
     * @return int
     */
    public function getNofPackets()
    {
        return $this->nof_packets;
    }

    /**
     * Generated from protobuf field <code>int32 nof_packets = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setNofPackets($var)
    {
        GPBUtil::checkInt32($var);
        $this->nof_packets = $var;

        return $this;
    }

}

