<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace Sealution\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TestThroughPutRespMsg</code>
 */
class TestThroughPutRespMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 idx = 1;</code>
     */
    protected $idx = 0;
    /**
     * Generated from protobuf field <code>bytes test_data = 2;</code>
     */
    protected $test_data = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_rm = 3;</code>
     */
    protected $date_time_rm = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_cm = 4;</code>
     */
    protected $date_time_cm = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $idx
     *     @type string $test_data
     *     @type \Google\Protobuf\Timestamp $date_time_rm
     *     @type \Google\Protobuf\Timestamp $date_time_cm
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mainmessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 idx = 1;</code>
     * @return int
     */
    public function getIdx()
    {
        return $this->idx;
    }

    /**
     * Generated from protobuf field <code>int32 idx = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIdx($var)
    {
        GPBUtil::checkInt32($var);
        $this->idx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes test_data = 2;</code>
     * @return string
     */
    public function getTestData()
    {
        return $this->test_data;
    }

    /**
     * Generated from protobuf field <code>bytes test_data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTestData($var)
    {
        GPBUtil::checkString($var, False);
        $this->test_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_rm = 3;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getDateTimeRm()
    {
        return $this->date_time_rm;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_rm = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDateTimeRm($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->date_time_rm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_cm = 4;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getDateTimeCm()
    {
        return $this->date_time_cm;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time_cm = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDateTimeCm($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->date_time_cm = $var;

        return $this;
    }

}

