<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/mainmessage.proto

namespace Sealution/Messages;

if (false) {
    /**
     * This class is deprecated. Use Sealution/Messages\TestMsg\eMsgType instead.
     * @deprecated
     */
    class TestMsg_eMsgType {}
}
class_exists(TestMsg\eMsgType::class);
@trigger_error('Sealution/Messages\TestMsg_eMsgType is deprecated and will be removed in the next major release. Use Sealution/Messages\TestMsg\eMsgType instead', E_USER_DEPRECATED);

