<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/mainmessage.proto

namespace Sealution\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TestMsg</code>
 */
class TestMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.TestMsg.eMsgType msg_type = 1;</code>
     */
    protected $msg_type = 0;
    protected $OneOfMsg;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $msg_type
     *     @type \Sealution/Messages\TestThroughPutMsg $test_throughput
     *     @type \Sealution/Messages\TestRestartDeviceMsg $test_restart_device
     * }
     */
    public function __construct($data = NULL) {
        \Sealution\Messages\Mainmessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.TestMsg.eMsgType msg_type = 1;</code>
     * @return int
     */
    public function getMsgType()
    {
        return $this->msg_type;
    }

    /**
     * Generated from protobuf field <code>.TestMsg.eMsgType msg_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgType($var)
    {
        GPBUtil::checkEnum($var, \Sealution/Messages\TestMsg_eMsgType::class);
        $this->msg_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TestThroughPutMsg test_throughput = 2;</code>
     * @return \Sealution/Messages\TestThroughPutMsg
     */
    public function getTestThroughput()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.TestThroughPutMsg test_throughput = 2;</code>
     * @param \Sealution/Messages\TestThroughPutMsg $var
     * @return $this
     */
    public function setTestThroughput($var)
    {
        GPBUtil::checkMessage($var, \Sealution/Messages\TestThroughPutMsg::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TestRestartDeviceMsg test_restart_device = 3;</code>
     * @return \Sealution/Messages\TestRestartDeviceMsg
     */
    public function getTestRestartDevice()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.TestRestartDeviceMsg test_restart_device = 3;</code>
     * @param \Sealution/Messages\TestRestartDeviceMsg $var
     * @return $this
     */
    public function setTestRestartDevice($var)
    {
        GPBUtil::checkMessage($var, \Sealution/Messages\TestRestartDeviceMsg::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getOneOfMsg()
    {
        return $this->whichOneof("OneOfMsg");
    }

}

