<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/mainmessage.proto

namespace Sealution/Messages;

if (false) {
    /**
     * This class is deprecated. Use Sealution/Messages\TestRespMsg\eMsgType instead.
     * @deprecated
     */
    class TestRespMsg_eMsgType {}
}
class_exists(TestRespMsg\eMsgType::class);
@trigger_error('Sealution/Messages\TestRespMsg_eMsgType is deprecated and will be removed in the next major release. Use Sealution/Messages\TestRespMsg\eMsgType instead', E_USER_DEPRECATED);

