<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace Sealution\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SensorDataMsg</code>
 */
class SensorDataMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time = 1;</code>
     */
    protected $date_time = null;
    /**
     * Generated from protobuf field <code>bytes bt_id = 2;</code>
     */
    protected $bt_id = '';
    /**
     * Generated from protobuf field <code>int32 rssi = 3;</code>
     */
    protected $rssi = 0;
    /**
     * Generated from protobuf field <code>bytes data = 4;</code>
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $date_time
     *     @type string $bt_id
     *     @type int $rssi
     *     @type string $data
     * }
     */
    public function __construct($data = NULL) {
        \Sealution\Messages\Mainmessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time = 1;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getDateTime()
    {
        return $this->date_time;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDateTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->date_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes bt_id = 2;</code>
     * @return string
     */
    public function getBtId()
    {
        return $this->bt_id;
    }

    /**
     * Generated from protobuf field <code>bytes bt_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBtId($var)
    {
        GPBUtil::checkString($var, False);
        $this->bt_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rssi = 3;</code>
     * @return int
     */
    public function getRssi()
    {
        return $this->rssi;
    }

    /**
     * Generated from protobuf field <code>int32 rssi = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRssi($var)
    {
        GPBUtil::checkInt32($var);
        $this->rssi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 4;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

