<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainmessage.proto

namespace Sealution\Messages\BTChipDataMsg;

/**
 * Protobuf type <code>BTChipDataMsg.eMsgType</code>
 */
class eMsgType
{
    /**
     * Generated from protobuf enum <code>MSG_TYPE_BTCHIP_SENSORDATA = 0;</code>
     */
    const MSG_TYPE_BTCHIP_SENSORDATA = 0;
    /**
     * Generated from protobuf enum <code>MSG_TYPE_BTCHIP_GET_CONFIG = 1;</code>
     */
    const MSG_TYPE_BTCHIP_GET_CONFIG = 1;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(eMsgType::class, \Sealution\Messages\BTChipDataMsg_eMsgType::class);

